title: 'FUN (version 1.0)'
logo: /assets/img/fun.png 
google_analytics:
theme: jekyll-theme-minimal
description: |
   Data mining and  optimization: refactored responsibly<br>
   &bullet; <a href="rows.md">rows</a><br>
   &bullet; <a href="row.md">row</a> 
    
  
